# Generated by Django 5.2.5 on 2025-08-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='curiosidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Descargas_user_movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=150)),
                ('id_movie', models.CharField(max_length=150)),
                ('fecha_descarga', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='genero_movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_movie', models.CharField(max_length=150)),
                ('id_genero', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('fecha_lanzamiento', models.DateField()),
                ('duracion', models.IntegerField()),
                ('archivo', models.FileField(upload_to='movies/')),
                ('poster', models.ImageField(upload_to='posters/')),
                ('autores', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Movie_curiosidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_movie', models.CharField(max_length=150)),
                ('id_curiosidades', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_movie', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_conexion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
