# Generated by Django 5.2.5 on 2025-09-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='autores',
            field=models.CharField(help_text='Lista de autores o estudio', max_length=250),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duracion',
            field=models.IntegerField(help_text='Duración en minutos'),
        ),
    ]
