# Generated by Django 5.2.5 on 2025-09-02 01:58

from django.db import migrations
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Movie = apps.get_model('core', 'Movie')
    for peli in Movie.objects.all():
        if not peli.slug:
            peli.slug = slugify(peli.titulo)
            peli.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movie_slug_alter_movie_autores_alter_movie_duracion'),
    ]

    operations = [
        migrations.RunPython(
            populate_slugs,
            reverse_code=migrations.RunPython.noop
        ),
    ]