# Generated by Django 5.2.5 on 2025-09-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250901_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='movies/'),
        ),
    ]
