# Generated by Django 5.2.5 on 2025-09-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_movie_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='enlace_externo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
