# Generated by Django 5.2.5 on 2025-09-04 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_movie_enlace_externo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
        migrations.CreateModel(
            name='OpinionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=250)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opiniones_generales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opinión General',
                'verbose_name_plural': 'Opiniones Generales',
            },
        ),
    ]
