# Generated by Django 5.2.5 on 2025-09-06 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_movie_poster_opiniongeneral'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='opiniongeneral',
            unique_together={('user',)},
        ),
    ]
