# Generated by Django 5.2.5 on 2025-09-06 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_opiniongeneral_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='opiniongeneral',
            unique_together=set(),
        ),
    ]
